### ISSUE TITLE
Field is not displayed properly when you Translatable

### ISSUE THREAD

**Issue by scramatte** [outl1ne/nova-trumbowyg-field#1]
Hi,

I'm using your Trumbowyg field with your other field NovaTranslatable.
When you use both at same time they are displayed inccorrectly.

![image](https://user-images.githubusercontent.com/188766/213025522-78db14c4-ab4f-4ef4-bd1d-be5395d80ea5.png)

```php
...
 return [
            Text::make(__('serviceDesk.title'), 'title')
              ->translatable(),

            Trumbowyg::make(__('serviceDesk.message'), 'message')
             ->size('w-full')
             ->hideFromIndex()
             ->alwaysShow()
             ->withMeta(['options' => [
                 'btns' => [
                    ['strong', 'italic'],
                    ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                 ],
             ]])
             ->translatable(),
        ];
...
````

Can you fix it?
Regards

**Comment by richard-raadi** [comment]
Hello!

Unfortunately I am not able to reproduce your issue on a barebones project (Image attached below).

Would it be possible for you to share a bit more specifics of the packages you are using?

We are testing here with the latest available package versions:

`"spatie/laravel-translatable": "^6.3"`
`"outl1ne/nova-translatable": "^2.1"`
`"outl1ne/nova-trumbowyg-field": "^1.1"`

I do see you are using the ->size() method on the field but I do not find any reference for it from the Nova documentation or any of our packages. Is it some other package you are using?

What Laravel version you are using?

What Nova version are you using?

It would help us the best, to find an solution to your issue, if you would provide a step-by-step to reproduce your incorrect result.

Please open up a new issue if it persists with a reproducible step-by-step instructions provided.

Best regards

<img width="1720" alt="image" src="https://user-images.githubusercontent.com/69033947/220849494-32503711-1991-49db-93b8-286e27dbf497.png">

**Comment by scramatte** [comment]
The issue is related to grid  plugin
https://github.com/codenco-dev/nova-grid-system
