### ISSUE TITLE
Style the field to be more Nova look and feel?

### ISSUE THREAD

**Issue by scramatte** [outl1ne/nova-trumbowyg-field#2]
Hi,

Does it possible to style the field to be more Nova look and feel?

Regards

**Comment by richard-raadi** [comment]
Hello!

Thanks for your interest in our project! 

The field you're referring to is functional and meets our current design standards, but we're always open to new ideas and improvements. 

If you have any specific suggestions for how to give it more of a Nova look and feel, we'd love to hear them! We're an open source project and welcome contributions, so if you're up for it, feel free to submit a pull request with your changes.

Best regards

**Comment by scramatte** [comment]
Hi,

What I mean is that corners of the field are not rounded. It can be probably solved by the following css, but as I can't rebuild field locally, I can't make PR (see: #4 )

```css
.trumbowyg-editor, .trumbowyg-editor {
  border-radius: 0.25rem !important;
}
```

Regards
