### ISSUE TITLE
dependsOn not showing the field

### ISSUE THREAD

**Issue by mitchkramez** [outl1ne/nova-trumbowyg-field#3]
First, thank you for the great nova field! I seem to be having an issue with the dependsOn feature in the latest Nova 4.x. The Trumbowyg field never shows up when checking the box. If the field was visible at load, it does hide it, but checking the box does not bring it back. I have to save the form to get it to show. Here's a snippet of my code below, which was/is working if i just switch it to a text field.

```
Boolean::make('Show logout message', 'has_logout_message')
                ->help('Shows logout message rather than redirecting to login.')
                ->hideFromIndex(),

            Trumbowyg::make('Logout Message', 'logout_message')
                ->fullWidth()
                ->hide()
                ->dependsOn('has_logout_message', function (Trumbowyg $field, NovaRequest $request, FormData $formData) {
                    if ($formData->has_logout_message == 1) {
                        $field->show();
                    }
                })
                ->help('Content for the logout screen.')->hideFromIndex()
                ->options($this->trumbowygOptions),
```
Using:
Nova 4.26.3
Nova Trumbowyg Field 1.1.2

Thanks again for the great package and any ideas you might have 😀

**Comment by ndrez-outl1ne** [comment]
Hi, check if the release [1.1.3](https://github.com/outl1ne/nova-trumbowyg-field/releases/tag/1.1.3) works for you. Some packages were updated and the code rebuilt.
